### ISSUE TITLE
Missing distance_map.png

### ISSUE THREAD

**Issue by bkhnk48** [Arena-Rosnav/arena-simulation-setup#13]
I run the script:
`roslaunch arena_bringup start_arena.launch  simulator:=flatland  task_mode:=scenario  map_file:=map0  model:=agvota`
But the program generates an error:
```
Traceback (most recent call last):
  File "/home/ukr/arena_ws/devel/lib/map_distance_server/map_distance_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/ukr/arena_ws/src/arena-rosnav/utils/ros/rosnodes/map_distance_server/scripts/map_distance_node.py", line 270, in <module>
    MapDistanceServer()
  File "/home/ukr/arena_ws/src/arena-rosnav/utils/ros/rosnodes/map_distance_server/scripts/map_distance_node.py", line 40, in __init__
    self.produce_distance_map()
  File "/home/ukr/arena_ws/src/arena-rosnav/utils/ros/rosnodes/map_distance_server/scripts/map_distance_node.py", line 53, in produce_distance_map
    self.new_map_data = list(self._get_map_with_distances())
  File "/home/ukr/arena_ws/src/arena-rosnav/utils/ros/rosnodes/map_distance_server/scripts/map_distance_node.py", line 154, in _get_map_with_distances
    coordinates_with_length[self._get_index(x, y)] = dist
OverflowError: cannot convert float infinity to integer
[distance_server-6] process has died [pid 84021, exit code 1, cmd /home/ukr/arena_ws/devel/lib/map_distance_server/map_distance_node.py __name:=distance_server __log:=/home/ukr/.ros/log/dba27574-9652-11ee-9302-41d8ab6d6478/distance_server-6.log].
log file: /home/ukr/.ros/log/dba27574-9652-11ee-9302-41d8ab6d6478/distance_server-6*.log
```

It causes my roslaunch could not finish it job. I guess the simulation-setup does not create "distance_map.png" which is read in the line 27 of "arena-rosnav/utils/ros/rosnodes/map_distance_server/scripts/map_distance_node.py"

**Comment by voshch** [comment]
resolved in #136
